### PR TITLE
exercise for the ternary operator

### PR DESCRIPTION
**Pull request by ConnyOnny**
Again I didn't add this to the Readme properly as I have no easy way of generating the required Rust playground link. I hope you like the exercise and don't mind adding it to the Readme.

### CODE REVIEW

**Comment by carols10cents** [comment]
It's totally not a problem for me to add it to the readme, don't worry about it :)

Just to check, this exercise is meant to showcase the fact that there *isn't* a ternary operator in rust and you'll need to use if/else, right? Just making sure I understand the exercise's intent :)

**Comment by ConnyOnny** [comment]
Yes it's meant to show how you can use Rust's if-then-else as a ternary operator because it is an expression and not (like in C or Java) a statement.

**Comment by ConnyOnny** [comment]
Should we make this more clear in the hint comments?

**Comment by carols10cents** [comment]
Yup, that's what I ended up doing -- I also decided this would be a great start to a section on `if`, so I moved it there!!! Thank you so much for your contribution!! :gift:

**Pull request merged**
